# Generated by Django 5.2 on 2025-05-25 15:33

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='VaccinationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('send_notification', models.BooleanField(
                    default=True, verbose_name='Gửi thông báo công khai')),
            ],
            options={
                'verbose_name': 'Đợt tiêm cộng đồng',
                'verbose_name_plural': 'Đợt tiêm cộng đồng',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                 help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                 max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True,
                 max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True,
                 max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True,
                 max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False,
                 help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(
                    default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('phone', models.CharField(blank=True,
                 max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed_profile', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                 related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                 related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('injection_time', models.DateTimeField()),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('NOT_VACCINATED', 'NOT_VACCINATED'), (
                    'VACCINATED', 'VACCINATED'), ('MISSED', 'MISSED')], default='NOT_VACCINATED', max_length=20)),
                ('note', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='injections', to=settings.AUTH_USER_MODEL)),
                ('vaccination_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='injections', to='vaccines.vaccinationcampaign')),
            ],
            options={
                'verbose_name': 'Lịch tiêm',
                'verbose_name_plural': 'Lịch tiêm',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('order_desc', models.CharField(max_length=255)),
                ('vnp_TransactionNo', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('vnp_ResponseCode', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('vnp_TmnCode', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('vnp_PayDate', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('vnp_BankCode', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('vnp_CardType', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('injection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='notifications', to='vaccines.injection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='private_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='PublicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('vaccine_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='public_notification', to='vaccines.vaccinationcampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('injection', ckeditor.fields.RichTextField()),
                ('patient', models.TextField()),
                ('effects', ckeditor.fields.RichTextField()),
                ('disease', models.CharField(max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('cates', models.ManyToManyField(blank=True,
                 related_name='vaccines', to='vaccines.category')),
            ],
            options={
                'verbose_name': 'Vacxin',
                'verbose_name_plural': 'Vacxin',
            },
        ),
        migrations.AddField(
            model_name='vaccinationcampaign',
            name='vaccine',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='order_details', to='vaccines.order')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='order_details', to='vaccines.vaccine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='injection',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='injections', to='vaccines.vaccine'),
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('days_after_previous', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='doses', to='vaccines.vaccine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='notification_status', to=settings.AUTH_USER_MODEL)),
                ('public_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='notification_status', to='vaccines.publicnotification')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='vaccines_no_user_id_5a165c_idx')],
                'unique_together': {('user', 'public_notification')},
            },
        ),
        migrations.AddIndex(
            model_name='injection',
            index=models.Index(fields=[
                               'user', 'vaccination_campaign', 'active'], name='vaccines_in_user_id_7f877b_idx'),
        ),
        migrations.AddIndex(
            model_name='injection',
            index=models.Index(
                fields=['injection_time'], name='vaccines_in_injecti_8d5284_idx'),
        ),
    ]
