# Generated by Django 5.2 on 2025-04-24 04:54

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('days_after_previous', models.IntegerField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_time', models.DateTimeField()),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaccines.dose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccination_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccinationcampaign')),
            ],
        ),
    ]
