# Generated by Django 5.2 on 2025-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_vaccinationcampaign_dose_injection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='outline',
        ),
        migrations.AddField(
            model_name='dose',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
