# Generated by Django 5.2 on 2025-06-05 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterField(
            model_name='privatenotification',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicnotification',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
