# Generated by Django 5.2 on 2025-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/static/images/avatar.png', max_length=255),
        ),
    ]
