# Generated by Django 5.2 on 2025-04-27 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0007_vaccinationcampaign_vaccine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='injection',
            options={'verbose_name': 'Lịch tiêm', 'verbose_name_plural': 'Lịch tiêm'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='vaccinationcampaign',
            options={'verbose_name': 'Đợt tiêm cộng đồng', 'verbose_name_plural': 'Đợt tiêm cộng đồng'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Vacxin', 'verbose_name_plural': 'Vacxin'},
        ),
        migrations.AddField(
            model_name='dose',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dose',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dose',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='injection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='injection',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='injection',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vaccinationcampaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccinationcampaign',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vaccinationcampaign',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
