# Generated by Django 5.2 on 2025-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0008_alter_category_options_alter_injection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dose',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='injection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='injection',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcampaign',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcampaign',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
