# Generated by Django 5.2 on 2025-04-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0009_alter_dose_created_date_alter_dose_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
