# Generated by Django 5.2 on 2025-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0010_user_is_completed_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
