# Generated by Django 5.2 on 2025-05-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0011_vaccine_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injection',
            name='dose',
        ),
        migrations.AddField(
            model_name='injection',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='vaccines.vaccine'),
        ),
        migrations.AlterField(
            model_name='injection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='injection',
            name='vaccination_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='vaccines.vaccinationcampaign'),
        ),
    ]
