# Generated by Django 5.2 on 2025-05-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0012_remove_injection_dose_injection_vaccine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
