# Generated by Django 5.2 on 2025-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0013_injection_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='injection',
            name='status',
            field=models.CharField(choices=[('NOT_VACCINATED', 'NOT_VACCINATED'), ('VACCINATED', 'VACCINATED'), ('MISSED', 'MISSED')], default='NOT_VACCINATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='injection',
            index=models.Index(fields=['user', 'vaccination_campaign', 'active'], name='vaccines_in_user_id_7f877b_idx'),
        ),
        migrations.AddIndex(
            model_name='injection',
            index=models.Index(fields=['injection_time'], name='vaccines_in_injecti_8d5284_idx'),
        ),
    ]
