# Generated by Django 5.2 on 2025-05-08 17:45

import django.db.models.deletion
import vaccines.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0015_remove_vaccine_manual_remove_vaccine_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injection',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default=vaccines.models.NotificationType['PRIVATE'], max_length=20)),
                ('injection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vaccines.injection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-notification_date'],
            },
        ),
    ]
