# Generated by Django 5.2 on 2025-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0016_alter_injection_number_privatenotification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicnotification',
            options={},
        ),
    ]
