# Generated by Django 5.2 on 2025-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0018_privatenotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationcampaign',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Gửi thông báo công khai'),
        ),
    ]
