# Generated by Django 5.2 on 2025-05-17 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0020_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('order_desc', models.CharField(max_length=255)),
                ('vnp_TransactionNo', models.CharField(max_length=255)),
                ('vnp_ResponseCode', models.CharField(max_length=10)),
                ('vnp_TmnCode', models.CharField(max_length=255)),
                ('vnp_PayDate', models.DateTimeField(auto_now_add=True)),
                ('vnp_BankCode', models.CharField(max_length=255)),
                ('vnp_CardType', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='vaccines.order')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='vaccines.vaccine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
