# Generated by Django 5.2 on 2025-05-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0021_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vnp_BankCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnp_CardType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnp_PayDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnp_ResponseCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnp_TmnCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vnp_TransactionNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
